package com.branchlight.backend.search.fetch;

public enum PageFetchFailureType {
    MALFORMED_URL,
    UNSUPPORTED_SCHEME,
    BLOCKED_DESTINATION,
    DNS_FAILURE,
    CONNECTION_TIMEOUT,
    RESPONSE_TIMEOUT,
    CONNECTION_FAILURE,
    HTTP_ERROR,
    INVALID_REDIRECT,
    REDIRECT_LOOP,
    TOO_MANY_REDIRECTS,
    UNSUPPORTED_CONTENT_TYPE,
    UNSUPPORTED_CONTENT_ENCODING,
    MALFORMED_RESPONSE,
    RESPONSE_TOO_LARGE,
    INTERRUPTED,
    UNEXPECTED_ERROR
}
